[pytest]
#python_files = *test.py
#python_functions = test_sum_positive_nums
#markers = positive_test: только позитивные тесты
markers =
    positive: tests for positive scenarios
    negative: tests for negative scenarios



